apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cstacks.cstack.app.com
spec:
  group: cstack.app.com
  names:
    kind: CStack
    listKind: CStackList
    plural: cstacks
    singular: cstack
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CStack is the Schema for the cstacks API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CStackSpec defines the desired state of CStack
          properties:
            database:
              type: string
            access_secret:
              type: string
            access_key:
              type: string
            default:
              type: object
              properties:
                version:
                  type: string
                cluster:
                  type: string #master-slave/single/cluster
        status:
          description: CStackStatus defines the observed state of CStack
          type: object
          properties:
              job:
                type: string
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
